# Generated by Cursor AI - Daily markdown report from DB

import sys
from pathlib import Path

_root = Path(__file__).resolve().parent.parent
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))

from scripts.build_report import build_report, write_report

__all__ = ["build_report", "write_report"]
