# Generated by Cursor AI - Daily markdown report from DB

from __future__ import annotations

import os
from collections import Counter
from typing import List, Optional

from classify.us_relevance import filter_signals_by_us_gate
from report.advisory import build_account_briefs, build_sec_company_briefs, enrich_signal, is_sec_signal
from store import get_connection, get_signals_for_report


def build_report(
    db_path: str,
    report_date: str,
    reports_dir: str,
    top_n: int = 15,
    min_score_targets: int = 45,
    secondary_whitelist: Optional[List[str]] = None,
) -> str:
    conn = get_connection(db_path)
    raw_signals = get_signals_for_report(conn, report_date, min_score=0, top_n=max(top_n * 10, 100))
    signals = sorted(
        [
            enrich_signal(signal)
            for signal in filter_signals_by_us_gate(raw_signals, secondary_whitelist=secondary_whitelist)
        ],
        key=lambda item: (item.get("total_score", 0), item.get("time_to_strain", 0)),
        reverse=True,
    )
    core_signals = [signal for signal in signals if not is_sec_signal(signal)]
    sec_briefs = build_sec_company_briefs(signals, limit=8)
    new_count = len(signals)
    account_briefs = build_account_briefs(signals, limit=8, min_move_rank=1)
    segments_list = []
    if core_signals:
        seg_counts = Counter(s.get("segment", "Operator") for s in core_signals)
        segments_list = [{"segment": k, "cnt": v} for k, v in seg_counts.most_common()]
    companies = [
        s
        for s in core_signals
        if (s.get("company") or "").strip() and s.get("total_score", 0) >= min_score_targets
    ]
    conn.close()

    sell_ahead_moves = ("Track target account", "Warm research", "Prepare outreach", "Contact now")
    sell_ahead = [s for s in core_signals if s.get("recommended_move") in sell_ahead_moves]

    lines = [
        f"# Mining Market Intelligence â€“ {report_date}",
        "",
        "*Scope: US-based companies only*",
        "",
        f"**New signals today:** {new_count}",
        "",
        "## Top signals by score",
        "",
    ]
    for s in core_signals[:top_n]:
        company = f" [{s['company']}]" if s.get("company") else ""
        country_suffix = ""
        if s.get("company"):
            cc = s.get("company_country") or "TBD"
            country_suffix = f" â€” Country: {cc}"
        lines.append(f"- **{s['signal_summary'][:200]}**{company}{country_suffix}")
        lines.append(
            f"  - {s['segment']} | {s['category']} | {s['posture']} | Score: {s['total_score']} | [Link]({s['link']})"
        )
        lines.append(f"  - Recommended move: {s['recommended_move']}")
        if s.get("total_score", 0) >= 40:
            lines.append(f"  - Score rationale: {s['score_rationale']}")
        if s.get("source_tier") == "secondary_whitelisted":
            lines.append(
                "  - **US relevance (Secondary source):** Basis: "
                + (s.get("us_relevance_basis") or "")
                + " | Execution angle: "
                + (s.get("execution_angle") or "")
            )
        elif s.get("mining_com_source_page"):
            lines.append(
                "  - **US relevance (Mining.com):** Source page: "
                + s.get("mining_com_source_page", "")
                + " | Basis: "
                + (s.get("us_relevance_basis") or "")
            )
        else:
            lines.append("  - **US relevance:** Basis: " + (s.get("us_relevance_basis") or ""))
        lines.append("")
        lines.append("  **Time-to-pain:**")
        lines.append(f"  - Horizon: {s['time_to_pain_horizon']}")
        lines.append(f"  - Reason: {s['time_to_pain_reason']}")
        lines.append("")
        lines.append("  **Buyer trigger mapping:**")
        lines.append(f"  - Likely role: {s['likely_role']}")
        lines.append(f"  - Function: {s['buyer_function']}")
        lines.append(f"  - Trigger moment: {s['trigger_moment']}")
        lines.append("")
        lines.append("  **FP360 first move:**")
        lines.append(f"  - Entry angle: {s['entry_angle']}")
        lines.append(f"  - Language to use: {s['language_to_use']}")
        lines.append(f"  - Language to avoid: {s['language_to_avoid']}")
        lines.append(f"  - Initial scope (2â€“4 weeks): {s['initial_scope']}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## SEC Filing Monitor")
    lines.append("")
    if sec_briefs:
        for brief in sec_briefs:
            lines.append(f"- **{brief['company']}**")
            lines.append(
                f"  - Lead filing: {brief['top_form']} | Focus: {brief['top_focus']} | Materiality: {brief['materiality']} | Recommended move: {brief['recommended_move']} | [Link]({brief['link']})"
            )
            lines.append(f"  - Why it matters: {brief['why_it_matters']}")
            lines.append(
                f"  - Recent filing mix: {brief['recent_forms']} | Total recent filings: {brief['filing_count']}"
            )
    else:
        lines.append("- No SEC filing items surfaced today.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Sell-ahead shortlist (Next 90â€“180 days)")
    lines.append("")
    if sell_ahead:
        for s in sell_ahead[:20]:
            company = f" [{s['company']}]" if s.get("company") else ""
            country_suffix = ""
            if s.get("company"):
                cc = s.get("company_country") or "TBD"
                country_suffix = f" â€” Country: {cc}"
            lines.append(
                f"- **{s['signal_summary'][:200]}**{company}{country_suffix} â€” {s['recommended_move']} | {s['posture']} | Score: {s['total_score']} | [Link]({s['link']})"
            )
    else:
        lines.append("None above threshold today; review top signals manually.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Accounts To Work Today")
    lines.append("")
    if account_briefs:
        for brief in account_briefs:
            lines.append(
                f"- **{brief['company']}** â€” {brief['recommended_move']} | {brief['posture']} | Score: {brief['score']} | Signals: {brief['signal_count']}"
            )
            lines.append(f"  - Why now: {brief['why_now']}")
            lines.append(f"  - Likely buyer: {brief['likely_role']} ({brief['buyer_function']})")
            lines.append(f"  - Trigger to watch: {brief['trigger_moment']}")
            lines.append(f"  - First move: {brief['entry_angle']}")
            lines.append(f"  - Initial scope: {brief['initial_scope']}")
            if brief.get("link"):
                lines.append(f"  - Anchor signal: [Link]({brief['link']})")
    else:
        lines.append("- No company briefs cleared the account-work threshold today.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## By segment")
    lines.append("")
    for seg in segments_list:
        lines.append(f"- **{seg['segment']}:** {seg['cnt']}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Companies to target")
    lines.append("")
    seen = set()
    for c in companies:
        name = (c.get("company") or "").strip()
        if not name or name in seen:
            continue
        seen.add(name)
        cc = c.get("company_country") or "TBD"
        basis = c.get("us_relevance_basis", "")
        mc_page = c.get("mining_com_source_page", "")
        exec_angle = c.get("execution_angle", "")
        if c.get("source_tier") == "secondary_whitelisted":
            rel_line = f"US relevance (Secondary source): Basis: {basis} | Execution angle: {exec_angle}"
        elif mc_page:
            rel_line = f"US relevance (Mining.com): Source page: {mc_page} | Basis: {basis}"
        else:
            rel_line = f"US relevance: Basis: {basis}"
        lines.append(
            f"- **{name}** â€“ Country: {cc} â€“ {c['recommended_move']} | {c['posture']} (score {c['total_score']}) | {rel_line} â€“ {c['signal_summary'][:100]}... [Link]({c['link']})"
        )
    if not seen:
        lines.append("- No companies extracted above threshold; review top signals for manual targeting.")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("## Glossary")
    lines.append("")
    lines.append(
        "**How to read** â€” Each signal line shows: **Segment** | **Category** | **Posture** | **Score** | Link."
    )
    lines.append(
        "- **Segment:** Type of player (Operator, EPCM, Contractor, OEM, Supplier, Startup/Platform)."
    )
    lines.append("- **Category:** Type of development (Growth, Entry, Change, Risk, Transition).")
    lines.append(
        "- **Posture:** Recommended BD stance: Monitor â†’ Prepare POV â†’ Target accounts â†’ Proactive outreach (higher score = more urgency)."
    )
    lines.append("- **Score:** Heuristic 0â€“100 from impact, time-to-strain, fit, and access.")
    lines.append("")
    lines.append("**FP360 Opportunity Score (0â€“100)**")
    lines.append(
        "- **What it represents:** A heuristic measure of how likely a company-level change will create near- to mid-term business operations or supply chain pain where FP360 services are relevant. Directional, not predictive."
    )
    lines.append(
        "- **Scoring dimensions:** Operational impact (0â€“30); Time-to-strain (0â€“30); FP360 service fit (0â€“25); Engagement feasibility (0â€“15)."
    )
    lines.append(
        "- **Score brackets:** 0â€“24 Monitor | 25â€“39 Monitor / Prepare POV | 40â€“54 Prepare POV | 55â€“69 Target accounts | 70â€“84 Proactive outreach | 85â€“100 Immediate outreach / priority."
    )
    lines.append(
        "- **Scoring rules (governance):** Scores must decay if no follow-on signals appear. No single uncorroborated item jumps from <30 to >70. Repeated signals compound. New entrants bias Time-to-strain upward. Technical/geological items cap Operational impact at 10 unless downstream ops/SCM explicit. Keep scores conservative when evidence is incomplete; mark unknowns TBD."
    )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Filtered out non-US companies based on current geography detection logic")
    lines.append("")
    return "\n".join(lines)


def write_report(
    db_path: str,
    report_date: str,
    reports_dir: str,
    top_n: int = 15,
    min_score_targets: int = 45,
    secondary_whitelist: Optional[List[str]] = None,
) -> str:
    os.makedirs(reports_dir, exist_ok=True)
    content = build_report(
        db_path,
        report_date,
        reports_dir,
        top_n,
        min_score_targets,
        secondary_whitelist=secondary_whitelist,
    )
    path = os.path.join(reports_dir, f"{report_date}.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path


__all__ = ["build_report", "write_report"]
