#!/usr/bin/env python3
# Generated by Cursor AI - Daily mining market intelligence: ingest -> classify -> store -> report

import sys
from datetime import date
from pathlib import Path

# project root
ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from config_loader import load_config
from store import (
    init_db,
    get_connection,
    dedupe_key_exists,
    source_link_exists,
    update_source_item_by_link,
    insert_raw,
    insert_signal,
)
from ingest import fetch_all_feeds, fetch_sec_watchlist_items, fetch_watchlist_press_releases
from classify import classify, score_dimensions, posture, confidence
from classify.rules import SEGMENT_RULES, CATEGORY_RULES, PRESSURE_POINT_RULES
from extract import extract_company
from report import write_report


def main() -> None:
    cfg = load_config(ROOT)
    db_path = str(ROOT / cfg["paths"]["db"])
    reports_dir = str(ROOT / cfg["paths"]["reports_dir"])
    report_cfg = cfg.get("report", {})
    top_n = report_cfg.get("top_n", 15)
    min_score_targets = report_cfg.get("min_score_targets", 45)
    watchlist_cfg = cfg.get("watchlist", {})

    init_db(db_path)
    conn = get_connection(db_path)
    today = date.today().isoformat()
    ingested_at = date.today().isoformat() + "T00:00:00"

    feeds = cfg.get("rss_feeds", [])
    company_watchlist = cfg.get("company_watchlist", [])
    if not feeds:
        print("No rss_feeds configured")
        conn.close()
        return
    user_agent = cfg.get("user_agent", "SteelpointOperationsIntel/2.0")

    items = fetch_all_feeds(feeds, user_agent)
    items.extend(fetch_watchlist_press_releases(company_watchlist, user_agent))
    items.extend(
        fetch_sec_watchlist_items(
            company_watchlist,
            user_agent,
            lookback_days=int(watchlist_cfg.get("sec_lookback_days", 30)),
            max_items_per_company=int(watchlist_cfg.get("sec_max_items_per_company", 10)),
        )
    )
    new_signals = 0

    try:
        for it in items:
            key = it["dedupe_key"]
            if dedupe_key_exists(conn, key) or source_link_exists(conn, it["source_name"], it["link"]):
                if it["source_name"] == "SEC EDGAR":
                    update_source_item_by_link(
                        conn,
                        it["source_name"],
                        it["link"],
                        it["title"],
                        it["summary"],
                        it["tags"],
                    )
                continue
            raw_id = insert_raw(
                conn,
                dedupe_key=key,
                source_url=it["source_url"],
                source_name=it["source_name"],
                title=it["title"],
                link=it["link"],
                published=it["published"],
                summary=it["summary"],
                tags=it["tags"],
                us_relevant=it["us_relevant"],
                ingested_at=ingested_at,
            )
            if it["us_relevant"] not in ("Yes", "Maybe"):
                continue
            text = f"{it['title']} {it['summary']}"
            seg = classify(text, SEGMENT_RULES, "Operator")
            cat = classify(text, CATEGORY_RULES, "Change")
            pp = classify(text, PRESSURE_POINT_RULES, "Supply Chain")
            impact, tts, fit, access = score_dimensions(text)
            total = impact + tts + fit + access
            company = (it.get("watchlist_company") or "").strip() or extract_company(it["title"], it["summary"]) or ""

            source_url = (it.get("source_url") or "").lower()
            mining_com_source_page = None
            if "mining.com" in source_url:
                mining_com_source_page = "US-focused page" if "region/usa" in source_url else "Global page"

            insert_signal(
                conn,
                raw_id=raw_id,
                dedupe_key=key,
                date_detected=today,
                company=company,
                segment=seg,
                signal_summary=(it["title"][:280] or ""),
                category=cat,
                source_name=it["source_name"],
                impact=impact,
                time_to_strain=tts,
                fit=fit,
                access=access,
                total_score=total,
                confidence=confidence(total),
                pressure_point=pp,
                posture=posture(total),
                tags=(it["tags"][:200] or ""),
                notes=(it["summary"][:450] or ""),
                link=it["link"],
                mining_com_source_page=mining_com_source_page,
                watchlist_company=(it.get("watchlist_company") or ""),
                watchlist_us_relevance_basis=(it.get("watchlist_us_relevance_basis") or ""),
            )
            new_signals += 1
        conn.commit()
    finally:
        conn.close()

    secondary_whitelist = cfg.get("secondary_whitelist") or []
    out_path = write_report(db_path, today, reports_dir, top_n=top_n, min_score_targets=min_score_targets, secondary_whitelist=secondary_whitelist)
    print(f"Done. New signals: {new_signals}. Report: {out_path}")


if __name__ == "__main__":
    main()
