#!/usr/bin/env python3
# Generated by Cursor AI - Weekly Insight Brief: aggregate last N days, synthesize 5-7 insights, write report

import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from config_loader import load_config
from report import write_weekly_report
from store import init_db


def main() -> None:
    cfg = load_config(ROOT)
    db_path = str(ROOT / cfg["paths"]["db"])
    init_db(db_path)
    reports_weekly_dir = str(ROOT / cfg["paths"].get("reports_weekly_dir", "reports/weekly"))
    weekly_cfg = cfg.get("weekly", {})
    days = weekly_cfg.get("days", 7)
    min_score = weekly_cfg.get("min_score", 0)
    min_insights = weekly_cfg.get("min_insights", 5)
    max_insights = weekly_cfg.get("max_insights", 7)
    secondary_whitelist = cfg.get("secondary_whitelist") or []

    end_date = date.today()
    out_path = write_weekly_report(
        db_path,
        end_date,
        reports_weekly_dir,
        days=days,
        min_score=min_score,
        min_insights=min_insights,
        max_insights=max_insights,
        secondary_whitelist=secondary_whitelist,
    )
    print(f"Insight Brief written: {out_path}")


if __name__ == "__main__":
    main()
