# Generated by Cursor AI
from .db import (
    get_connection,
    init_db,
    dedupe_key_exists,
    source_link_exists,
    update_source_item_by_link,
    insert_raw,
    insert_signal,
    get_signals_for_report,
    get_new_signals_count,
    get_companies_to_target,
    get_segment_summary,
    get_signals_in_date_range,
)
