# Generated by Cursor AI - SQLite schema and store for mining market intelligence

import sqlite3
from pathlib import Path
from typing import Any, List, Optional

SCHEMA = """
CREATE TABLE IF NOT EXISTS raw_items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    dedupe_key TEXT UNIQUE NOT NULL,
    source_url TEXT NOT NULL,
    source_name TEXT,
    title TEXT NOT NULL,
    link TEXT NOT NULL,
    published TEXT,
    summary TEXT,
    tags TEXT,
    us_relevant TEXT,
    ingested_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    raw_id INTEGER NOT NULL,
    dedupe_key TEXT UNIQUE NOT NULL,
    date_detected TEXT NOT NULL,
    company TEXT,
    segment TEXT NOT NULL,
    signal_summary TEXT NOT NULL,
    category TEXT NOT NULL,
    source_name TEXT NOT NULL,
    impact INTEGER NOT NULL,
    time_to_strain INTEGER NOT NULL,
    fit INTEGER NOT NULL,
    access INTEGER NOT NULL,
    total_score INTEGER NOT NULL,
    confidence TEXT NOT NULL,
    pressure_point TEXT NOT NULL,
    posture TEXT NOT NULL,
    tags TEXT,
    notes TEXT,
    link TEXT NOT NULL,
    mining_com_source_page TEXT,
    watchlist_company TEXT,
    watchlist_us_relevance_basis TEXT,
    FOREIGN KEY (raw_id) REFERENCES raw_items(id)
);

CREATE INDEX IF NOT EXISTS idx_signals_date ON signals(date_detected);
CREATE INDEX IF NOT EXISTS idx_signals_score ON signals(total_score DESC);
CREATE INDEX IF NOT EXISTS idx_signals_posture ON signals(posture);
CREATE INDEX IF NOT EXISTS idx_raw_dedupe ON raw_items(dedupe_key);
"""


def get_connection(db_path: str) -> sqlite3.Connection:
    Path(db_path).parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


def init_db(db_path: str) -> None:
    conn = get_connection(db_path)
    conn.executescript(SCHEMA)
    try:
        conn.execute("ALTER TABLE signals ADD COLUMN mining_com_source_page TEXT")
    except sqlite3.OperationalError:
        pass
    try:
        conn.execute("ALTER TABLE signals ADD COLUMN tags TEXT")
    except sqlite3.OperationalError:
        pass
    try:
        conn.execute("ALTER TABLE signals ADD COLUMN watchlist_company TEXT")
    except sqlite3.OperationalError:
        pass
    try:
        conn.execute("ALTER TABLE signals ADD COLUMN watchlist_us_relevance_basis TEXT")
    except sqlite3.OperationalError:
        pass
    conn.commit()
    conn.close()


def dedupe_key_exists(conn: sqlite3.Connection, key: str) -> bool:
    cur = conn.execute(
        "SELECT 1 FROM raw_items WHERE dedupe_key = ? UNION SELECT 1 FROM signals WHERE dedupe_key = ?",
        (key, key),
    )
    return cur.fetchone() is not None


def source_link_exists(conn: sqlite3.Connection, source_name: str, link: str) -> bool:
    cur = conn.execute(
        "SELECT 1 FROM raw_items WHERE source_name = ? AND link = ? UNION SELECT 1 FROM signals WHERE source_name = ? AND link = ?",
        (source_name, link, source_name, link),
    )
    return cur.fetchone() is not None


def update_source_item_by_link(
    conn: sqlite3.Connection,
    source_name: str,
    link: str,
    title: str,
    summary: str,
    tags: str,
) -> None:
    conn.execute(
        "UPDATE raw_items SET title = ?, summary = ?, tags = ? WHERE source_name = ? AND link = ?",
        (title, summary, tags, source_name, link),
    )
    conn.execute(
        "UPDATE signals SET signal_summary = ?, notes = ?, tags = ? WHERE source_name = ? AND link = ?",
        (title, summary, tags, source_name, link),
    )


def insert_raw(
    conn: sqlite3.Connection,
    dedupe_key: str,
    source_url: str,
    source_name: str,
    title: str,
    link: str,
    published: str,
    summary: str,
    tags: str,
    us_relevant: str,
    ingested_at: str,
) -> int:
    cur = conn.execute(
        """INSERT INTO raw_items (dedupe_key, source_url, source_name, title, link, published, summary, tags, us_relevant, ingested_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (dedupe_key, source_url, source_name, title, link, published or "", summary or "", tags or "", us_relevant, ingested_at),
    )
    return cur.lastrowid


def insert_signal(
    conn: sqlite3.Connection,
    raw_id: int,
    dedupe_key: str,
    date_detected: str,
    company: str,
    segment: str,
    signal_summary: str,
    category: str,
    source_name: str,
    impact: int,
    time_to_strain: int,
    fit: int,
    access: int,
    total_score: int,
    confidence: str,
    pressure_point: str,
    posture: str,
    tags: Optional[str],
    notes: str,
    link: str,
    mining_com_source_page: Optional[str] = None,
    watchlist_company: Optional[str] = None,
    watchlist_us_relevance_basis: Optional[str] = None,
) -> None:
    conn.execute(
        """INSERT INTO signals (raw_id, dedupe_key, date_detected, company, segment, signal_summary, category, source_name,
           impact, time_to_strain, fit, access, total_score, confidence, pressure_point, posture, tags, notes, link,
           mining_com_source_page, watchlist_company, watchlist_us_relevance_basis)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
        (
            raw_id,
            dedupe_key,
            date_detected,
            company or "",
            segment,
            signal_summary,
            category,
            source_name,
            impact,
            time_to_strain,
            fit,
            access,
            total_score,
            confidence,
            pressure_point,
            posture,
            tags or "",
            notes or "",
            link,
            mining_com_source_page or None,
            watchlist_company or None,
            watchlist_us_relevance_basis or None,
        ),
    )


def get_signals_for_report(
    conn: sqlite3.Connection, date: str, min_score: int = 0, top_n: int = 100
) -> List[Any]:
    cur = conn.execute(
        """SELECT date_detected, company, segment, signal_summary, category, source_name,
                  impact, time_to_strain, fit, access, total_score, confidence, pressure_point, posture, tags, notes, link,
                  mining_com_source_page, watchlist_company, watchlist_us_relevance_basis
           FROM signals WHERE date_detected = ? AND total_score >= ?
           ORDER BY total_score DESC LIMIT ?""",
        (date, min_score, top_n),
    )
    return [dict(row) for row in cur.fetchall()]


def get_new_signals_count(conn: sqlite3.Connection, date: str) -> int:
    cur = conn.execute("SELECT COUNT(*) FROM signals WHERE date_detected = ?", (date,))
    return cur.fetchone()[0]


def get_companies_to_target(conn: sqlite3.Connection, date: str, min_score: int) -> List[dict]:
    cur = conn.execute(
        """SELECT company, segment, posture, total_score, signal_summary, link
           FROM signals WHERE date_detected = ? AND total_score >= ? AND company != ''
           ORDER BY total_score DESC""",
        (date, min_score),
    )
    return [dict(row) for row in cur.fetchall()]


def get_segment_summary(conn: sqlite3.Connection, date: str) -> List[dict]:
    cur = conn.execute(
        """SELECT segment, COUNT(*) AS cnt FROM signals WHERE date_detected = ?
           GROUP BY segment ORDER BY cnt DESC""",
        (date,),
    )
    return [dict(row) for row in cur.fetchall()]


def get_signals_in_date_range(
    conn: sqlite3.Connection, start_date: str, end_date: str, min_score: int = 0
) -> List[dict]:
    cur = conn.execute(
        """SELECT date_detected, company, segment, signal_summary, category, source_name,
                  impact, time_to_strain, fit, access, total_score, confidence, pressure_point, posture, tags, notes, link,
                  mining_com_source_page, watchlist_company, watchlist_us_relevance_basis
           FROM signals WHERE date_detected >= ? AND date_detected <= ? AND total_score >= ?
           ORDER BY total_score DESC, date_detected DESC""",
        (start_date, end_date, min_score),
    )
    return [dict(row) for row in cur.fetchall()]
