# Generated by Cursor AI - Multi-feed RSS ingestion

import hashlib
import re
import time
import urllib.request
import xml.etree.ElementTree as ET
from typing import List

try:
    import feedparser
except ImportError:
    feedparser = None

US_KEYWORDS = re.compile(
    r"\b(United States|U\.S\.|USA|Nevada|Arizona|Utah|Texas|Wyoming|Alaska|Idaho|New Mexico|Colorado|Montana|Minnesota|Michigan)\b",
    re.I,
)


def dedupe_key(link: str, title: str) -> str:
    h = hashlib.sha1((link.strip() + "|" + title.strip()).encode("utf-8")).hexdigest()
    return h[:16]


def _clean_summary(raw: str) -> str:
    return re.sub(r"\s+", " ", re.sub("<.*?>", "", raw or ""))[:500]


def _local_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def _text_content(elem: ET.Element) -> str:
    return "".join(elem.itertext()).strip()


def _find_child_text(elem: ET.Element, names: set[str]) -> str:
    for child in list(elem):
        if _local_name(child.tag) in names:
            text = _text_content(child)
            if text:
                return text
    return ""


def _find_link(elem: ET.Element) -> str:
    for child in list(elem):
        if _local_name(child.tag) != "link":
            continue
        href = child.attrib.get("href")
        if href:
            return href.strip()
        text = _text_content(child)
        if text:
            return text
    return ""


def _find_tags(elem: ET.Element) -> str:
    tags = []
    for child in list(elem):
        if _local_name(child.tag) != "category":
            continue
        tag = child.attrib.get("term") or _text_content(child)
        if tag:
            tags.append(tag.strip())
    return ",".join(tags)


def _parse_feed_with_stdlib(url: str, user_agent: str) -> List[dict]:
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": user_agent,
            "Accept": "application/rss+xml, application/atom+xml, application/xml, text/xml",
        },
    )
    with urllib.request.urlopen(req, timeout=30) as response:
        payload = response.read()

    root = ET.fromstring(payload)
    entries = []
    for elem in root.iter():
        local = _local_name(elem.tag)
        if local not in {"item", "entry"}:
            continue
        title = _find_child_text(elem, {"title"})
        link = _find_link(elem)
        published = _find_child_text(elem, {"published", "updated", "pubDate"})
        summary = _find_child_text(elem, {"summary", "description", "content"})
        tags = _find_tags(elem)
        text = f"{title} {summary}"
        us_relevant = "Yes" if US_KEYWORDS.search(text) else "Maybe"
        entries.append(
            {
                "dedupe_key": dedupe_key(link, title),
                "source_url": url,
                "source_name": "",
                "title": title,
                "link": link,
                "published": published,
                "summary": _clean_summary(summary),
                "tags": tags,
                "us_relevant": us_relevant,
            }
        )
    return entries


def fetch_feed(url: str, source_name: str, user_agent: str) -> List[dict]:
    if feedparser is None:
        items = _parse_feed_with_stdlib(url, user_agent)
        for item in items:
            item["source_name"] = source_name
        return items

    fp = feedparser.parse(url, request_headers={"User-Agent": user_agent})
    items = []
    for e in fp.entries:
        title = getattr(e, "title", "") or ""
        link = getattr(e, "link", "") or ""
        published = getattr(e, "published", "") or getattr(e, "updated", "") or ""
        summary = _clean_summary(getattr(e, "summary", "") or "")
        tags = ",".join([t.term for t in getattr(e, "tags", [])]) if hasattr(e, "tags") else ""
        text = f"{title} {summary}"
        us_relevant = "Yes" if US_KEYWORDS.search(text) else "Maybe"
        items.append({
            "dedupe_key": dedupe_key(link, title),
            "source_url": url,
            "source_name": source_name,
            "title": title,
            "link": link,
            "published": published,
            "summary": summary,
            "tags": tags,
            "us_relevant": us_relevant,
        })
    return items


def fetch_all_feeds(feed_configs: List[dict], user_agent: str, delay_seconds: float = 1.0) -> List[dict]:
    out = []
    for cfg in feed_configs:
        url = cfg.get("url", "").strip()
        name = cfg.get("name", url)
        if not url:
            continue
        try:
            items = fetch_feed(url, name, user_agent)
            out.extend(items)
        except Exception:
            pass
        time.sleep(delay_seconds)
    return out
