# Generated by Cursor AI - Company extraction from title/summary

import re
from typing import Optional

KNOWN_MINERS = sorted(
    {
        "A2Gold",
        "AOMC",
        "Albemarle",
        "Allied Critical",
        "Altius",
        "Anglo American",
        "Antofagasta",
        "Atlas Lithium",
        "Barrick",
        "BHP",
        "Cameco",
        "Caterpillar",
        "Cleveland-Cliffs",
        "Core Lithium",
        "Cyclic Materials",
        "Domestic Metals",
        "EnergyX",
        "Epiroc",
        "First Majestic",
        "First Quantum",
        "Fluor",
        "Freeport",
        "G Mining",
        "Glencore",
        "Halliburton",
        "Heelstone Renewable",
        "Hexagon",
        "Highland Copper",
        "Hitachi",
        "ION Minerals",
        "Jacobs",
        "Komatsu",
        "Liberty Gold",
        "Lithium Americas",
        "Lundin",
        "Lynas",
        "Macquarie",
        "Maptek",
        "McEwen Copper",
        "Mesabi Metallics",
        "Mosaic",
        "MP Materials",
        "Newmont",
        "NioCorp",
        "Nucor",
        "Odyssey",
        "Perenti",
        "PH7 Technologies",
        "Pilbara",
        "Red Mountain",
        "Rio Tinto",
        "Rock Tech",
        "Sandvik",
        "SQM",
        "St George",
        "Teck",
        "The Metals Royalty Company",
        "Trafigura",
        "UEC",
        "United States Antimony",
        "Uranium Energy",
        "USA Rare Earth",
        "Vale",
        "Versamet",
        "Vizsla",
        "Worley",
        "ioneer",
    }
)

_ENTITY_TOKEN = r"[A-Z][A-Za-z0-9&.+/-]*"
_ACTION_VERBS = (
    "acquire|acquires|acquiring|adds|advance|announces|appeal|appeals|award|awards|"
    "backs|begins|block|blocks|build|building|buy|buys|commissions|considers|"
    "debuts|discloses|draws|enters|expands|extends|eyes|go public|launches|lines up|"
    "merge|merger|merges|moves|pulls|raises|restarts|resumes|seeks|selected|selects|"
    "signs|starts|taps|targets|unveils|warns"
)

_COMPANY_PATTERNS = [
    r"\b(" + "|".join(re.escape(c) for c in KNOWN_MINERS) + r")\b",
    rf"\b({_ENTITY_TOKEN}(?:\s+{_ENTITY_TOKEN}){{0,4}})(?:'s|’s)\b",
    rf"\b({_ENTITY_TOKEN}(?:\s+{_ENTITY_TOKEN}){{0,4}})\s+(?:{_ACTION_VERBS})\b",
    rf"\b({_ENTITY_TOKEN}(?:\s+{_ENTITY_TOKEN}){{0,4}})\s+(?:Inc\.?|Corp\.?|Ltd\.?|LLC|plc|PLC)\b",
]

_BANNED_EXACT = {
    "Argentina",
    "Brazil",
    "British Columbia",
    "Chile",
    "Column",
    "Environmentalists",
    "France",
    "Goldman",
    "Kazakhstan",
    "Op-Ed",
    "Report",
    "South Korea",
    "The",
    "The Journal",
    "Trump",
    "US",
    "USA",
    "United States",
    "White House",
}

_BANNED_PREFIXES = (
    "A new ",
    "The ",
    "Top ",
)

_BANNED_TERMS = {
    "and",
    "energy",
    "for",
    "gold",
    "journal",
    "market",
    "metals",
    "mining",
    "report",
    "the",
    "us",
    "usa",
}


def _normalize_candidate(name: str) -> str:
    cleaned = re.sub(r"\s+", " ", name.replace("’", "'")).strip(" -,:;.'\"")
    cleaned = re.sub(r"(?:'s)$", "", cleaned, flags=re.I).strip()
    if cleaned.endswith("'"):
        cleaned = cleaned[:-1].strip()
    return cleaned


def _is_valid_candidate(name: str) -> bool:
    if not name or len(name) < 3:
        return False
    if name in _BANNED_EXACT:
        return False
    if any(name.startswith(prefix) for prefix in _BANNED_PREFIXES):
        return False
    words = name.split()
    if len(words) == 1 and words[0].lower() in _BANNED_TERMS:
        return False
    if all(word.lower() in _BANNED_TERMS for word in words):
        return False
    if re.fullmatch(r"\d+", name):
        return False
    return True


def extract_company(title: str, summary: str) -> Optional[str]:
    text = f"{title or ''} {summary or ''}"
    for pat in _COMPANY_PATTERNS:
        for match in re.finditer(pat, text):
            name = _normalize_candidate(match.group(1))
            if _is_valid_candidate(name):
                return name
    return None
