# Generated by Cursor AI
from .rules import (
    SEGMENT_RULES,
    CATEGORY_RULES,
    PRESSURE_POINT_RULES,
    classify,
    score_dimensions,
    posture,
    confidence,
)
from .us_relevance import apply_us_relevance_gate, filter_signals_by_us_gate
