# Generated by Cursor AI - Heuristic classification and scoring (from fp360_mi_runner)

import re
from typing import List, Tuple

SEGMENT_RULES = [
    ("EPCM", r"\b(EPCM|engineering|procurement\s+and\s+construction|Fluor|Jacobs|Worley)\b"),
    ("Contractor", r"\b(contractor|mining\s+services|earthworks|drilling|blasting)\b"),
    ("OEM", r"\b(Caterpillar|Komatsu|Sandvik|Epiroc|Hitachi|OEM)\b"),
    ("Supplier", r"\b(MRO|spares|consumables|parts|supplier)\b"),
    ("Startup/Platform", r"\b(startup|platform|software|AI|digital|automation)\b"),
]
CATEGORY_RULES = [
    ("Growth", r"\b(expand|expansion|ramp[-\s]?up|scale|increase production|growth)\b"),
    ("Entry", r"\b(enters? the U\.S\.|new entrant|launch|start operations|new project)\b"),
    ("Change", r"\b(ERP|implementation|restructure|reorg|operating model|transformation)\b"),
    ("Risk", r"\b(delay|shortage|disruption|cost overrun|missed|halt|suspend|bankrupt)\b"),
    ("Transition", r"\b(energy transition|battery|lithium|REE|rare earth|nickel|cobalt)\b"),
]
PRESSURE_POINT_RULES = [
    ("Procurement", r"\b(procurement|sourcing|tender|supplier|contract award)\b"),
    ("Inventory", r"\b(inventory|spares|MRO|stockout|overstock|warehouse)\b"),
    ("Planning", r"\b(plan|schedule|ramp|forecast|capacity)\b"),
    ("Supply Chain", r"\b(lead time|logistics|shipping|transport|port|rail)\b"),
    ("Operations", r"\b(operations|commission|startup|production|throughput)\b"),
]

_DIRECT_OPERATIONAL_TRIGGERS = re.compile(
    r"\b(restart|restarts|begins production|begin production|starts production|production start|"
    r"startup|commissioning|commissioned|launches .* plant|launches first .* plant|"
    r"starts construction|construction begins|build(?:ing)? .* plant|build(?:ing)? .* facility|"
    r"expands?|expansion|ramp[-\s]?up|processing plant|facility|contract award|awards contract|"
    r"selected for .* funding|local supply push|offtake|supplier deal)\b",
    re.I,
)
_CAPITAL_OR_OWNERSHIP_TRIGGERS = re.compile(
    r"\b(acquisition|acquire|merger|merge|joint venture|partnership|ipo|spac|financing|"
    r"investment|funding|raises? \$|ifc|debuts on nasdaq|go public)\b",
    re.I,
)
_CHANGE_TRIGGERS = re.compile(
    r"\b(restructure|strategic reset|operating model|erp|transformation|leadership|appointed|named)\b",
    re.I,
)
_PLANNING_TRIGGERS = re.compile(
    r"\b(plan|planning|capacity|forecast|schedule|review phase|environmental review|appeal|permit|tariff)\b",
    re.I,
)
_FP360_FIT_TRIGGERS = re.compile(
    r"\b(procurement|sourcing|supplier|inventory|planning|lead time|logistics|material flow|"
    r"throughput|startup|commission|production|construction|contractor|mobilization)\b",
    re.I,
)
_TRANSITION_MINERAL_TRIGGERS = re.compile(
    r"\b(lithium|rare earth|rare-earth|nickel|cobalt|graphite|uranium|antimony|critical minerals?)\b",
    re.I,
)
_ACCESS_TRIGGERS = re.compile(
    r"\b(appoints|named|joins as|new ceo|new coo|new cfo|vp operations|head of supply chain|"
    r"financing|raise|ipo|spac|investment|funding|selected|taps|partnership|ifc|nasdaq)\b",
    re.I,
)
_IMMEDIATE_TIME_TRIGGERS = re.compile(
    r"\b(immediate|this quarter|next month|coming months|this year|in 90 days|near[-\s]?term|"
    r"begins production|restart|startup|commission|launches|starts construction)\b",
    re.I,
)
_LONG_DATED_TIME_TRIGGERS = re.compile(r"\b(2027|2028|2029|2030|long[-\s]?term)\b", re.I)
_MACRO_COMMENTARY = re.compile(
    r"\b(op-ed|column|report|price target|gold price|copper price|ceasefire|traders weigh|"
    r"top 50|mining companies power through|reserves|market shift|war|remarks on truce)\b",
    re.I,
)
_ACTIONABLE_COMPANY_EVENT = re.compile(
    r"\b(project|plant|facility|mine|production|restart|startup|construction|expands?|review|"
    r"funding|financing|ipo|spac|merger|acquisition|offtake|contract|supply push|partner)\b",
    re.I,
)
_MINING_DOMAIN_TERMS = re.compile(
    r"\b(mine|mining|mineral|metals?|lithium|rare earth|rare-earth|uranium|antimony|"
    r"copper|gold|nickel|cobalt|graphite|ore|processing plant|smelter|refinery)\b",
    re.I,
)
_OFF_DOMAIN_ENERGY = re.compile(
    r"\b(solar|hydropower|gas plant|offshore assets|renewable power|power plant|oil and gas|"
    r"offshore|suriname|petronas|valaris|manaus)\b",
    re.I,
)


def classify(text: str, rules: List[Tuple[str, str]], default: str) -> str:
    for label, pattern in rules:
        if re.search(pattern, text, flags=re.I):
            return label
    return default


def score_dimensions(text: str) -> Tuple[int, int, int, int]:
    t = text.lower()
    impact = 5
    if _DIRECT_OPERATIONAL_TRIGGERS.search(t):
        impact += 12
    if _CHANGE_TRIGGERS.search(t):
        impact += 8
    if _CAPITAL_OR_OWNERSHIP_TRIGGERS.search(t):
        impact += 7
    if _PLANNING_TRIGGERS.search(t):
        impact += 5
    impact = min(30, impact)

    tts = 6
    if _IMMEDIATE_TIME_TRIGGERS.search(t):
        tts += 10
    if _PLANNING_TRIGGERS.search(t):
        tts += 6
    if _LONG_DATED_TIME_TRIGGERS.search(t):
        tts -= 2
    tts = max(0, min(30, tts))

    fit = 5
    if _FP360_FIT_TRIGGERS.search(t):
        fit += 12
    if _DIRECT_OPERATIONAL_TRIGGERS.search(t):
        fit += 8
    if _TRANSITION_MINERAL_TRIGGERS.search(t):
        fit += 4
    fit = min(25, fit)

    access = 3
    if _ACCESS_TRIGGERS.search(t):
        access += 6
    if _CAPITAL_OR_OWNERSHIP_TRIGGERS.search(t):
        access += 4
    if _CHANGE_TRIGGERS.search(t):
        access += 3
    access = min(15, access)

    if _MACRO_COMMENTARY.search(t) and not _ACTIONABLE_COMPANY_EVENT.search(t):
        impact = min(impact, 8)
        fit = min(fit, 6)
        access = min(access, 3)
    if _OFF_DOMAIN_ENERGY.search(t) and not _MINING_DOMAIN_TERMS.search(t):
        impact = min(impact, 6)
        tts = min(tts, 8)
        fit = min(fit, 4)
        access = min(access, 3)

    return impact, tts, fit, access


def posture(total_score: int) -> str:
    if total_score >= 70:
        return "Proactive outreach"
    if total_score >= 55:
        return "Target accounts"
    if total_score >= 40:
        return "Prepare POV"
    return "Monitor"


def confidence(total_score: int) -> str:
    if total_score >= 70:
        return "High"
    if total_score >= 40:
        return "Medium"
    return "Low"
