# Generated by Cursor AI - Primary vs secondary source whitelist. Secondary excluded by default.

import re
from typing import Optional, Tuple

# Mining.com is the only primary source (Tier-1 US-focused, Tier-2 global).
PRIMARY_SOURCE_PATTERN = "mining.com"

# Approved secondary sources ONLY when they explicitly reference US execution.
# Add source_name substrings or exact names (e.g. "SEC", "DOE", "Company Press Release").
# Empty = no secondary sources approved; only Mining.com signals pass.
SECONDARY_WHITELIST_NAMES = []

# Secondary sources may not independently score above this (no primary corroboration).
SECONDARY_SCORE_CAP = 55

# pressure_point -> Execution angle (Ops | SCM | Procurement | Planning | Logistics).
# If pressure_point not in map, secondary signal is excluded (TBD).
PRESSURE_POINT_TO_EXECUTION_ANGLE = {
    "Procurement": "Procurement",
    "Supply Chain": "SCM",
    "Planning": "Planning",
    "Operations": "Ops",
    "Inventory": "SCM",
    "Logistics": "Logistics",
}

MINING_DOMAIN_TERMS = re.compile(
    r"\b(mine|mining|mineral|metals?|lithium|rare earth|rare-earth|uranium|antimony|"
    r"copper|gold|nickel|cobalt|graphite|ore|processing plant|refinery|smelter|"
    r"concentrator|mill|drill|drilling|tailings|phosphate|potash)\b",
    re.I,
)
OFF_DOMAIN_ENERGY_TERMS = re.compile(
    r"\b(solar|hydropower|gas plant|offshore assets|renewable power|power plant|oil and gas|"
    r"offshore|petronas|valaris|manaus|water launch|siphon-fed)\b",
    re.I,
)


def _is_primary(source_name: str, source_url: str = "") -> bool:
    name = (source_name or "").lower()
    url = (source_url or "").lower()
    return PRIMARY_SOURCE_PATTERN in name or PRIMARY_SOURCE_PATTERN in url


def _is_secondary_whitelisted(source_name: str, source_url: str = "", whitelist: Optional[list] = None) -> bool:
    wl = whitelist if whitelist is not None else SECONDARY_WHITELIST_NAMES
    if not wl:
        return False
    name = (source_name or "").strip()
    url = (source_url or "").lower()
    for entry in wl:
        if entry and (entry.lower() in name.lower() or entry.lower() in url):
            return True
    return False


def get_source_tier(
    signal: dict,
    secondary_whitelist: Optional[list] = None,
) -> str:
    """
    Returns: primary_us | primary_global | secondary_whitelisted | secondary_excluded.
    """
    source_name = (signal.get("source_name") or "").strip()
    source_url = (signal.get("source_url") or "").strip()
    mc_page = (signal.get("mining_com_source_page") or "").strip()

    if _is_primary(source_name, source_url):
        return "primary_us" if mc_page == "US-focused page" else "primary_global"
    if _is_secondary_whitelisted(source_name, source_url, secondary_whitelist):
        return "secondary_whitelisted"
    return "secondary_excluded"


def get_execution_angle(pressure_point: str) -> Optional[str]:
    """Map pressure_point to Ops | SCM | Procurement | Planning | Logistics. None if TBD."""
    return PRESSURE_POINT_TO_EXECUTION_ANGLE.get((pressure_point or "").strip())


def is_mining_domain_signal(signal: dict) -> bool:
    text = " ".join(
        [
            signal.get("signal_summary") or signal.get("title") or "",
            signal.get("notes") or signal.get("summary") or "",
            signal.get("company") or "",
        ]
    ).strip()
    if not text:
        return False
    if OFF_DOMAIN_ENERGY_TERMS.search(text) and not MINING_DOMAIN_TERMS.search(text):
        return False
    return MINING_DOMAIN_TERMS.search(text) is not None


def apply_secondary_score_cap(signal: dict, tier: str) -> dict:
    """Cap total_score at SECONDARY_SCORE_CAP for secondary_whitelisted signals."""
    s = dict(signal)
    if tier == "secondary_whitelisted":
        score = s.get("total_score") or 0
        if score > SECONDARY_SCORE_CAP:
            s["total_score"] = SECONDARY_SCORE_CAP
            s["posture"] = "Prepare POV" if SECONDARY_SCORE_CAP >= 40 else "Monitor"
    return s
