# Generated by Cursor AI - US Relevance Gate: PASS / CONDITIONAL / REJECT. No inference; explicit text only.

import re
from typing import List, Optional, Tuple

# Explicit patterns only. Do not infer US relevance.

# PASS: US-based company (explicit wording)
PASS_US_BASED = re.compile(
    r"\b(US-based|U\.S\.-based|American company|headquartered in (the )?U\.S\.|"
    r"based in (the )?United States|incorporated in (the )?U\.S\.)\b",
    re.I,
)

# PASS: US asset / location (states or "in the United States", "U.S. facility", etc.)
PASS_US_ASSET = re.compile(
    r"\b(United States|U\.S\.|USA)\b.*\b(mine|facility|plant|project|operations|site|campus)\b|"
    r"\b(in|into) (the )?(United States|U\.S\.)\b|"
    r"\b(Nevada|Arizona|Utah|Texas|Wyoming|Alaska|Idaho|New Mexico|Colorado|Montana|Minnesota|Michigan)\b",
    re.I,
)

# PASS: US market entry (explicit)
PASS_US_MARKET_ENTRY = re.compile(
    r"\b(enters? (the )?U\.S\. (market|mining)|U\.S\. expansion|"
    r"expand(s|ing)? (into|in) (the )?U\.S\.|(enters?|entering) (the )?United States)\b",
    re.I,
)

# PASS: US supply chain / operations impact (explicit)
PASS_US_IMPACT = re.compile(
    r"\b(U\.S\. (supply chain|operations|suppliers|capacity|customers|market)\b|"
    r"impact on (the )?U\.S\.|(affects?|impact) (the )?U\.S\. (operations|supply)|"
    r"U\.S\. (operations|supply chain) (impact|affected))\b",
    re.I,
)

# CONDITIONAL: non-US story but explicit downstream US impact stated
CONDITIONAL_US_LINKAGE = re.compile(
    r"\b(downstream (impact|effect) on (the )?U\.S\.|"
    r"U\.S\. (suppliers|operations|capacity|market) (impact|affected|stated)|"
    r"(affects?|impact on) U\.S\. (operations|supply chain|suppliers|capacity))\b",
    re.I,
)

# REJECT: "North America" without explicit United States (do not infer US from North America)
NORTH_AMERICA_ONLY = re.compile(r"\bNorth America(n)?\b", re.I)
EXPLICIT_US = re.compile(
    r"\b(United States|U\.S\.|USA|Nevada|Arizona|Utah|Texas|Wyoming|Alaska|Idaho|"
    r"New Mexico|Colorado|Montana|Minnesota|Michigan)\b",
    re.I,
)

PASS_BASIS = {
    "us_based": "US-based company",
    "us_asset": "US asset",
    "us_market_entry": "US market entry",
    "us_impact": "US supply chain impact",
}
CONDITIONAL_BASIS = "Downstream impact on US operations/suppliers/capacity stated in source."


def apply_us_relevance_gate(
    title: str,
    summary: str,
    notes: str,
    company: str = "",
) -> Tuple[str, Optional[str]]:
    """
    Classify signal as PASS, CONDITIONAL, or REJECT. Only PASS/CONDITIONAL with non-empty basis proceed.
    Returns (PASS|CONDITIONAL|REJECT, basis or None). If basis would be TBD, returns (REJECT, None).
    """
    text = f"{title or ''} {summary or ''} {notes or ''} {company or ''}".strip()
    if not text:
        return "REJECT", None

    # REJECT: North America without explicit US (do not infer)
    if NORTH_AMERICA_ONLY.search(text) and not EXPLICIT_US.search(text):
        return "REJECT", None

    # PASS checks (explicit only)
    if PASS_US_BASED.search(text):
        return "PASS", PASS_BASIS["us_based"]
    if PASS_US_ASSET.search(text):
        return "PASS", PASS_BASIS["us_asset"]
    if PASS_US_MARKET_ENTRY.search(text):
        return "PASS", PASS_BASIS["us_market_entry"]
    if PASS_US_IMPACT.search(text):
        return "PASS", PASS_BASIS["us_impact"]

    # CONDITIONAL: explicit downstream US impact
    if CONDITIONAL_US_LINKAGE.search(text):
        return "CONDITIONAL", CONDITIONAL_BASIS

    # REJECT: no explicit US relevance
    return "REJECT", None


def _is_mining_com(signal: dict) -> bool:
    name = (signal.get("source_name") or "").strip()
    return "mining.com" in name.lower() or name == "MINING.com"


def _normalize_primary_source_page(signal: dict) -> str:
    source_page = (signal.get("mining_com_source_page") or "").strip()
    if source_page:
        return source_page

    source_url = (signal.get("source_url") or "").lower()
    if "region/usa" in source_url:
        return "US-focused page"
    if "mining.com" in source_url:
        return "Global page"

    # Historical rows may not carry enough metadata to distinguish page type.
    return "Primary page unspecified"


def filter_signals_by_us_gate(
    signals: list,
    secondary_whitelist: Optional[List[str]] = None,
) -> list:
    """
    Return only signals that pass the gate (PASS or CONDITIONAL with basis)
    AND pass source whitelist: primary (Mining.com) or secondary_whitelisted only.
    Secondary_excluded sources are dropped. Secondary_whitelisted require
    execution_angle (from pressure_point); if TBD, exclude. Score capped for secondary.
    """
    from classify.source_tier import (
        get_source_tier,
        get_execution_angle,
        is_mining_domain_signal,
        apply_secondary_score_cap,
    )

    out = []
    for s in signals:
        title = s.get("signal_summary") or s.get("title") or ""
        summary = s.get("notes") or s.get("summary") or ""
        notes = s.get("notes") or ""
        company = (s.get("company") or "").strip()
        verdict, basis = apply_us_relevance_gate(title, summary, notes, company)
        if (verdict, basis) == ("REJECT", None):
            manual_basis = (s.get("watchlist_us_relevance_basis") or "").strip()
            if manual_basis:
                verdict, basis = "PASS", manual_basis
        if verdict not in ("PASS", "CONDITIONAL") or not basis:
            continue

        tier = get_source_tier(s, secondary_whitelist)
        if tier == "secondary_excluded":
            continue

        if tier == "secondary_whitelisted":
            if not is_mining_domain_signal(s):
                continue
            execution_angle = get_execution_angle(s.get("pressure_point") or "")
            if not execution_angle:
                continue
            s = dict(s)
            s["us_relevance_basis"] = basis
            s["source_tier"] = tier
            s["execution_angle"] = execution_angle
            s = apply_secondary_score_cap(s, tier)
            out.append(s)
        else:
            if _is_mining_com(s):
                source_page = _normalize_primary_source_page(s)
            else:
                source_page = (s.get("mining_com_source_page") or "").strip()
            s = dict(s)
            s["us_relevance_basis"] = basis
            s["source_tier"] = tier
            s["mining_com_source_page"] = source_page
            out.append(s)
    return out
