from __future__ import annotations

from html import escape
import re


def _inline(text: str) -> str:
    text = escape(text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    return text


def markdown_fragment(markdown: str) -> str:
    lines = markdown.splitlines()
    parts: list[str] = []
    list_depth = 0

    def close_lists(target_depth: int = 0) -> None:
        nonlocal list_depth
        while list_depth > target_depth:
            parts.append("</ul>")
            list_depth -= 1

    for raw_line in lines:
        line = raw_line.rstrip()
        stripped = line.strip()
        if not stripped:
            close_lists(0)
            continue
        if stripped == "---":
            close_lists(0)
            parts.append("<hr />")
            continue
        if stripped.startswith("### "):
            close_lists(0)
            parts.append(f"<h3>{_inline(stripped[4:])}</h3>")
            continue
        if stripped.startswith("## "):
            close_lists(0)
            parts.append(f"<h2>{_inline(stripped[3:])}</h2>")
            continue
        if stripped.startswith("# "):
            close_lists(0)
            parts.append(f"<h1>{_inline(stripped[2:])}</h1>")
            continue
        if stripped.startswith("- "):
            indent = (len(line) - len(line.lstrip(" "))) // 2
            target_depth = indent + 1
            close_lists(target_depth)
            while list_depth < target_depth:
                parts.append("<ul>")
                list_depth += 1
            parts.append(f"<li>{_inline(stripped[2:])}</li>")
            continue
        close_lists(0)
        parts.append(f"<p>{_inline(stripped)}</p>")

    close_lists(0)
    return "\n".join(parts)


def _shell(title: str, body: str, subtitle: str = "", archive_url: str = "") -> str:
    subtitle_html = f"<p class=\"subtitle\">{escape(subtitle)}</p>" if subtitle else ""
    archive_html = f'<p class="archive"><a href="{archive_url}">Open report archive</a></p>' if archive_url else ""
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{escape(title)}</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f3efe6;
      --card: #fffdf8;
      --ink: #20201b;
      --muted: #615c50;
      --accent: #8c4a21;
      --rule: #ded4c1;
      --code: #f5ead9;
    }}
    body {{
      margin: 0;
      background: radial-gradient(circle at top, #fbf7ef 0%, var(--bg) 65%);
      color: var(--ink);
      font: 16px/1.55 Georgia, "Times New Roman", serif;
    }}
    .wrap {{
      max-width: 920px;
      margin: 0 auto;
      padding: 32px 20px 56px;
    }}
    .card {{
      background: var(--card);
      border: 1px solid var(--rule);
      border-radius: 18px;
      box-shadow: 0 10px 30px rgba(32, 32, 27, 0.08);
      padding: 28px 32px;
    }}
    h1, h2, h3 {{ line-height: 1.2; margin: 1.2em 0 0.45em; }}
    h1 {{ font-size: 2rem; margin-top: 0; }}
    h2 {{ font-size: 1.35rem; border-top: 1px solid var(--rule); padding-top: 1rem; }}
    h3 {{ font-size: 1.05rem; color: var(--accent); }}
    p, li {{ margin: 0.45em 0; }}
    ul {{ margin: 0.35em 0 0.8em 1.25rem; padding: 0; }}
    hr {{ border: 0; border-top: 1px solid var(--rule); margin: 1.25rem 0; }}
    a {{ color: var(--accent); }}
    code {{
      background: var(--code);
      border-radius: 4px;
      padding: 0.1em 0.35em;
      font: 0.92em Consolas, "Courier New", monospace;
    }}
    .subtitle, .archive {{
      color: var(--muted);
      margin-top: -0.35rem;
    }}
    .footer {{
      color: var(--muted);
      font-size: 0.92rem;
      margin-top: 1.25rem;
    }}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="card">
      <h1>{escape(title)}</h1>
      {subtitle_html}
      {archive_html}
      {body}
      <p class="footer">Generated by the FP360 mining market intelligence pipeline.</p>
    </div>
  </div>
</body>
</html>
"""


def render_markdown_page(title: str, markdown: str, subtitle: str = "") -> str:
    return _shell(title, markdown_fragment(markdown), subtitle=subtitle)


def render_markdown_email(title: str, markdown: str, archive_url: str = "") -> str:
    return _shell(title, markdown_fragment(markdown), archive_url=archive_url)
